In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("CarPrice_Assignment.csv")

In [4]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [5]:
df.shape

(205, 26)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    str
 3   fueltype          205 non-null    str
 4   aspiration        205 non-null    str
 5   doornumber        205 non-null    str
 6   carbody           205 non-null    str
 7   drivewheel        205 non-null    str
 8   enginelocation    205 non-null    str
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    str
 15  cylindernumber    205 non-null    str
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    str
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), str(10)
memory usage: 41.8 KB

In [7]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='str')

In [8]:
df.dtypes

car_ID                int64
symboling             int64
CarName                 str
fueltype                str
aspiration              str
doornumber              str
carbody                 str
drivewheel              str
enginelocation          str
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype              str
cylindernumber          str
enginesize            int64
fuelsystem              str
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [9]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [10]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_columns

C:\Users\AKSHAY\AppData\Local\Temp\ipykernel_26792\1797605437.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

Index(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber',
       'fuelsystem'],
      dtype='str')

In [11]:
y = df["price"]

In [12]:
X = df.drop("price", axis=1)

In [13]:
X.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22

In [14]:
X = df.select_dtypes(include=["int64", "float64"])

In [15]:
X = X.drop(columns=["price", "car_ID"])

In [16]:
X.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22

In [17]:
X = X.to_numpy()
y = y.to_numpy()

In [18]:
print(X.shape)
print(y.shape)

(205, 14)
(205,)

In [19]:
np.random.seed(42)

In [20]:
indices = np.random.permutation(len(X))

In [21]:
X = X[indices]
y = y[indices]

In [22]:
print(X.shape)
print(y.shape)

(205, 14)
(205,)

In [23]:
split_index = int(0.8 * len(X))

In [24]:
X_train = X[:split_index]
X_test = X[split_index:]

y_train = y[:split_index]
y_test = y[split_index:]

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(164, 14)
(41, 14)
(164,)
(41,)

In [26]:
X_train[:5]

array([[ 0.000e+00,  1.035e+02,  1.890e+02,  6.690e+01,  5.570e+01,
         3.230e+03,  2.090e+02,  3.620e+00,  3.390e+00,  8.000e+00,
         1.820e+02,  5.400e+03,  1.600e+01,  2.200e+01],
       [ 0.000e+00,  9.950e+01,  1.782e+02,  6.790e+01,  5.200e+01,
         3.053e+03,  1.310e+02,  3.130e+00,  3.400e+00,  7.000e+00,
         1.600e+02,  5.500e+03,  1.600e+01,  2.200e+01],
       [ 0.000e+00,  9.720e+01,  1.734e+02,  6.520e+01,  5.470e+01,
         2.302e+03,  1.200e+02,  3.330e+00,  3.470e+00,  8.500e+00,
         9.700e+01,  5.200e+03,  2.700e+01,  3.400e+01],
       [ 3.000e+00,  9.910e+01,  1.866e+02,  6.650e+01,  5.610e+01,
         2.658e+03,  1.210e+02,  3.540e+00,  3.070e+00,  9.310e+00,
         1.100e+02,  5.250e+03,  2.100e+01,  2.800e+01],
       [-1.000e+00,  1.100e+02,  1.909e+02,  7.030e+01,  5.870e+01,
         3.750e+03,  1.830e+02,  3.580e+00,  3.640e+00,  2.150e+01,
         1.230e+02,  4.350e+03,  2.200e+01,  2.500e+01]])

In [27]:
mu = np.mean(X_train, axis=0)

In [28]:
mu

array([8.90243902e-01, 9.85298780e+01, 1.73306098e+02, 6.57890244e+01,
       5.37268293e+01, 2.52945732e+03, 1.24951220e+02, 3.32463415e+00,
       3.25768293e+00, 1.02903049e+01, 1.01579268e+02, 5.12134146e+03,
       2.55121951e+01, 3.10121951e+01])

In [29]:
sigma = np.std(X_train, axis=0)

In [30]:
sigma

array([1.23472222e+00, 5.96343717e+00, 1.23417430e+01, 2.10142264e+00,
       2.47613235e+00, 5.06258434e+02, 3.92067386e+01, 2.65909370e-01,
       3.11117866e-01, 4.18024148e+00, 3.76221563e+01, 4.91080844e+02,
       6.48214038e+00, 6.76882002e+00])

In [31]:
X_train = (X_train - mu) / sigma

In [32]:
X_test = (X_test - mu) / sigma

In [33]:
w = np.zeros(X_train.shape[1])
b = 0

In [34]:
predictions = X_train @ w + b

In [35]:
predictions[:5]

array([0., 0., 0., 0., 0.])

In [36]:
errors = predictions - y_train

In [37]:
squared_errors = errors ** 2

In [38]:
total_squared_error = np.sum(squared_errors)

In [39]:
m = len(y_train)

In [40]:
cost = total_squared_error / (2 * m)

In [41]:
cost

np.float64(113957753.35498138)

In [42]:
dj_db = np.sum(errors) / m

In [43]:
dj_dw = (X_train.T @ errors) / m

In [44]:
alpha = 0.01

In [45]:
w = w - alpha * dj_dw
b = b - alpha * dj_db

In [46]:
def compute_cost(X, y, w, b):
    m = len(y)
    predictions = X @ w + b
    errors = predictions - y
    cost = np.sum(errors ** 2) / (2 * m)
    return cost

In [47]:
def compute_gradient(X, y, w, b):
    m = len(y)
    errors = (X @ w + b) - y
    dj_dw = (X.T @ errors) / m
    dj_db = np.sum(errors) / m
    return dj_dw, dj_db

In [60]:

def gradient_descent(X, y, w, b, alpha, num_iterations):
    J_history = []

    for i in range(num_iterations):
        dj_dw, dj_db = compute_gradient(X, y, w, b)

        w = w - alpha * dj_dw
        b = b - alpha * dj_db

        J_history.append(compute_cost(X, y, w, b))

    return w, b, J_history

In [61]:

w, b, J_history = gradient_descent(
    X_train, y_train,
    np.zeros(X_train.shape[1]), 0,
    alpha=0.01,
    num_iterations=1000
)

predictions = X_test @ w + b

test_errors = predictions - y_test
mae = np.mean(np.abs(test_errors))
rmse = np.sqrt(np.mean(test_errors ** 2))

print("Initial cost:", J_history[0])
print("Final cost:", J_history[-1])
print("Test MAE:", mae)
print("Test RMSE:", rmse)

Initial cost: 109639037.23088928
Final cost: 4344815.228200334
Test MAE: 2865.1470461778545
Test RMSE: 3846.3382383026556

In [58]:

predictions = X_test @ w + b

print("Predicted prices:", predictions[:5])
print("Actual prices:", y_test[:5])

Predicted prices: [22004.06838321 19036.7475375  13824.58234517 18257.06156039
 12592.43480822]
Actual prices: [15690. 15040. 11549. 18420. 10795.]

In [62]:

test_errors = predictions - y_test

mae = np.mean(np.abs(test_errors))
rmse = np.sqrt(np.mean(test_errors ** 2))

print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Absolute Error (MAE): 2865.1470461778545
Root Mean Squared Error (RMSE): 3846.3382383026556

In [63]:

for i, cost in enumerate(J_history, start=1):
    print(f"Iteration {i}: Cost = {cost:.2f}")

Iteration 1: Cost = 109639037.23
Iteration 2: Cost = 105683204.68
Iteration 3: Cost = 102047589.14
Iteration 4: Cost = 98694915.05
Iteration 5: Cost = 95592608.07
Iteration 6: Cost = 92712193.73
Iteration 7: Cost = 90028773.25
Iteration 8: Cost = 87520566.53
Iteration 9: Cost = 85168513.74
Iteration 10: Cost = 82955928.01
Iteration 11: Cost = 80868192.63
Iteration 12: Cost = 78892497.05
Iteration 13: Cost = 77017606.69
Iteration 14: Cost = 75233662.35
Iteration 15: Cost = 73532005.15
Iteration 16: Cost = 71905024.08
Iteration 17: Cost = 70346022.91
Iteration 18: Cost = 68849104.24
Iteration 19: Cost = 67409068.37
Iteration 20: Cost = 66021325.09
Iteration 21: Cost = 64681816.78
Iteration 22: Cost = 63386951.32
Iteration 23: Cost = 62133543.61
Iteration 24: Cost = 60918764.54
Iteration 25: Cost = 59740096.46
Iteration 26: Cost = 58595294.38
Iteration 27: Cost = 57482352.08
Iteration 28: Cost = 56399472.57
Iteration 29: Cost = 55345042.27
Iteration 30: Cost = 54317608.55
Iteration 31: Cost = 53315860.06
Iteration 32: Cost = 52338609.57
Iteration 33: Cost = 51384779.03
Iteration 34: Cost = 50453386.47
Iteration 35: Cost = 49543534.60
Iteration 36: Cost = 48654400.83
Iteration 37: Cost = 47785228.53
Iteration 38: Cost = 46935319.45
Iteration 39: Cost = 46104027.04
Iteration 40: Cost = 45290750.62
Iteration 41: Cost = 44494930.30
Iteration 42: Cost = 43716042.48
Iteration 43: Cost = 42953595.99
Iteration 44: Cost = 42207128.64
Iteration 45: Cost = 41476204.22
Iteration 46: Cost = 40760409.88
Iteration 47: Cost = 40059353.80
Iteration 48: Cost = 39372663.19
Iteration 49: Cost = 38699982.45
Iteration 50: Cost = 38040971.68
Iteration 51: Cost = 37395305.23
Iteration 52: Cost = 36762670.49
Iteration 53: Cost = 36142766.86
Iteration 54: Cost = 35535304.72
Iteration 55: Cost = 34940004.68
Iteration 56: Cost = 34356596.74
Iteration 57: Cost = 33784819.69
Iteration 58: Cost = 33224420.49
Iteration 59: Cost = 32675153.76
Iteration 60: Cost = 32136781.29
Iteration 61: Cost = 31609071.64
Iteration 62: Cost = 31091799.73
Iteration 63: Cost = 30584746.56
Iteration 64: Cost = 30087698.82
Iteration 65: Cost = 29600448.68
Iteration 66: Cost = 29122793.52
Iteration 67: Cost = 28654535.68
Iteration 68: Cost = 28195482.26
Iteration 69: Cost = 27745444.96
Iteration 70: Cost = 27304239.85
Iteration 71: Cost = 26871687.26
Iteration 72: Cost = 26447611.60
Iteration 73: Cost = 26031841.21
Iteration 74: Cost = 25624208.27
Iteration 75: Cost = 25224548.64
Iteration 76: Cost = 24832701.78
Iteration 77: Cost = 24448510.62
Iteration 78: Cost = 24071821.47
Iteration 79: Cost = 23702483.93
Iteration 80: Cost = 23340350.78
Iteration 81: Cost = 22985277.92
Iteration 82: Cost = 22637124.29
Iteration 83: Cost = 22295751.76
Iteration 84: Cost = 21961025.09
Iteration 85: Cost = 21632811.85
Iteration 86: Cost = 21310982.35
Iteration 87: Cost = 20995409.57
Iteration 88: Cost = 20685969.12
Iteration 89: Cost = 20382539.14
Iteration 90: Cost = 20085000.28
Iteration 91: Cost = 19793235.62
Iteration 92: Cost = 19507130.64
Iteration 93: Cost = 19226573.11
Iteration 94: Cost = 18951453.14
Iteration 95: Cost = 18681663.01
Iteration 96: Cost = 18417097.23
Iteration 97: Cost = 18157652.41
Iteration 98: Cost = 17903227.27
Iteration 99: Cost = 17653722.55
Iteration 100: Cost = 17409041.03
Iteration 101: Cost = 17169087.41
Iteration 102: Cost = 16933768.33
Iteration 103: Cost = 16702992.29
Iteration 104: Cost = 16476669.65
Iteration 105: Cost = 16254712.55
Iteration 106: Cost = 16037034.90
Iteration 107: Cost = 15823552.33
Iteration 108: Cost = 15614182.18
Iteration 109: Cost = 15408843.42
Iteration 110: Cost = 15207456.65
Iteration 111: Cost = 15009944.07
Iteration 112: Cost = 14816229.41
Iteration 113: Cost = 14626237.95
Iteration 114: Cost = 14439896.44
Iteration 115: Cost = 14257133.11
Iteration 116: Cost = 14077877.62
Iteration 117: Cost = 13902061.01
Iteration 118: Cost = 13729615.73
Iteration 119: Cost = 13560475.54
Iteration 120: Cost = 13394575.55
Iteration 121: Cost = 13231852.15
Iteration 122: Cost = 13072242.98
Iteration 123: Cost = 12915686.96
Iteration 124: Cost = 12762124.18
Iteration 125: Cost = 12611495.95
Iteration 126: Cost = 12463744.74
Iteration 127: Cost = 12318814.16
Iteration 128: Cost = 12176648.95
Iteration 129: Cost = 12037194.94
Iteration 130: Cost = 11900399.03
Iteration 131: Cost = 11766209.18
Iteration 132: Cost = 11634574.38
Iteration 133: Cost = 11505444.65
Iteration 134: Cost = 11378770.98
Iteration 135: Cost = 11254505.33
Iteration 136: Cost = 11132600.63
Iteration 137: Cost = 11013010.73
Iteration 138: Cost = 10895690.40
Iteration 139: Cost = 10780595.31
Iteration 140: Cost = 10667681.99
Iteration 141: Cost = 10556907.85
Iteration 142: Cost = 10448231.13
Iteration 143: Cost = 10341610.92
Iteration 144: Cost = 10237007.09
Iteration 145: Cost = 10134380.31
Iteration 146: Cost = 10033692.05
Iteration 147: Cost = 9934904.52
Iteration 148: Cost = 9837980.68
Iteration 149: Cost = 9742884.23
Iteration 150: Cost = 9649579.59
Iteration 151: Cost = 9558031.86
Iteration 152: Cost = 9468206.87
Iteration 153: Cost = 9380071.08
Iteration 154: Cost = 9293591.64
Iteration 155: Cost = 9208736.34
Iteration 156: Cost = 9125473.61
Iteration 157: Cost = 9043772.51
Iteration 158: Cost = 8963602.69
Iteration 159: Cost = 8884934.41
Iteration 160: Cost = 8807738.53
Iteration 161: Cost = 8731986.45
Iteration 162: Cost = 8657650.18
Iteration 163: Cost = 8584702.24
Iteration 164: Cost = 8513115.72
Iteration 165: Cost = 8442864.22
Iteration 166: Cost = 8373921.88
Iteration 167: Cost = 8306263.33
Iteration 168: Cost = 8239863.71
Iteration 169: Cost = 8174698.65
Iteration 170: Cost = 8110744.27
Iteration 171: Cost = 8047977.13
Iteration 172: Cost = 7986374.28
Iteration 173: Cost = 7925913.20
Iteration 174: Cost = 7866571.84
Iteration 175: Cost = 7808328.56
Iteration 176: Cost = 7751162.15
Iteration 177: Cost = 7695051.83
Iteration 178: Cost = 7639977.22
Iteration 179: Cost = 7585918.32
Iteration 180: Cost = 7532855.57
Iteration 181: Cost = 7480769.75
Iteration 182: Cost = 7429642.03
Iteration 183: Cost = 7379453.98
Iteration 184: Cost = 7330187.48
Iteration 185: Cost = 7281824.80
Iteration 186: Cost = 7234348.55
Iteration 187: Cost = 7187741.69
Iteration 188: Cost = 7141987.50
Iteration 189: Cost = 7097069.59
Iteration 190: Cost = 7052971.90
Iteration 191: Cost = 7009678.68
Iteration 192: Cost = 6967174.49
Iteration 193: Cost = 6925444.18
Iteration 194: Cost = 6884472.93
Iteration 195: Cost = 6844246.17
Iteration 196: Cost = 6804749.65
Iteration 197: Cost = 6765969.37
Iteration 198: Cost = 6727891.62
Iteration 199: Cost = 6690502.96
Iteration 200: Cost = 6653790.21
Iteration 201: Cost = 6617740.45
Iteration 202: Cost = 6582341.00
Iteration 203: Cost = 6547579.45
Iteration 204: Cost = 6513443.60
Iteration 205: Cost = 6479921.53
Iteration 206: Cost = 6447001.53
Iteration 207: Cost = 6414672.11
Iteration 208: Cost = 6382922.02
Iteration 209: Cost = 6351740.23
Iteration 210: Cost = 6321115.92
Iteration 211: Cost = 6291038.48
Iteration 212: Cost = 6261497.50
Iteration 213: Cost = 6232482.80
Iteration 214: Cost = 6203984.37
Iteration 215: Cost = 6175992.40
Iteration 216: Cost = 6148497.29
Iteration 217: Cost = 6121489.61
Iteration 218: Cost = 6094960.12
Iteration 219: Cost = 6068899.76
Iteration 220: Cost = 6043299.63
Iteration 221: Cost = 6018151.04
Iteration 222: Cost = 5993445.44
Iteration 223: Cost = 5969174.45
Iteration 224: Cost = 5945329.86
Iteration 225: Cost = 5921903.61
Iteration 226: Cost = 5898887.82
Iteration 227: Cost = 5876274.73
Iteration 228: Cost = 5854056.76
Iteration 229: Cost = 5832226.46
Iteration 230: Cost = 5810776.53
Iteration 231: Cost = 5789699.81
Iteration 232: Cost = 5768989.28
Iteration 233: Cost = 5748638.07
Iteration 234: Cost = 5728639.42
Iteration 235: Cost = 5708986.71
Iteration 236: Cost = 5689673.46
Iteration 237: Cost = 5670693.29
Iteration 238: Cost = 5652039.98
Iteration 239: Cost = 5633707.39
Iteration 240: Cost = 5615689.53
Iteration 241: Cost = 5597980.52
Iteration 242: Cost = 5580574.58
Iteration 243: Cost = 5563466.05
Iteration 244: Cost = 5546649.38
Iteration 245: Cost = 5530119.14
Iteration 246: Cost = 5513869.98
Iteration 247: Cost = 5497896.68
Iteration 248: Cost = 5482194.09
Iteration 249: Cost = 5466757.19
Iteration 250: Cost = 5451581.04
Iteration 251: Cost = 5436660.79
Iteration 252: Cost = 5421991.71
Iteration 253: Cost = 5407569.13
Iteration 254: Cost = 5393388.49
Iteration 255: Cost = 5379445.31
Iteration 256: Cost = 5365735.21
Iteration 257: Cost = 5352253.86
Iteration 258: Cost = 5338997.05
Iteration 259: Cost = 5325960.64
Iteration 260: Cost = 5313140.56
Iteration 261: Cost = 5300532.83
Iteration 262: Cost = 5288133.54
Iteration 263: Cost = 5275938.85
Iteration 264: Cost = 5263945.02
Iteration 265: Cost = 5252148.34
Iteration 266: Cost = 5240545.21
Iteration 267: Cost = 5229132.07
Iteration 268: Cost = 5217905.46
Iteration 269: Cost = 5206861.95
Iteration 270: Cost = 5195998.20
Iteration 271: Cost = 5185310.93
Iteration 272: Cost = 5174796.91
Iteration 273: Cost = 5164453.00
Iteration 274: Cost = 5154276.09
Iteration 275: Cost = 5144263.14
Iteration 276: Cost = 5134411.18
Iteration 277: Cost = 5124717.28
Iteration 278: Cost = 5115178.57
Iteration 279: Cost = 5105792.24
Iteration 280: Cost = 5096555.54
Iteration 281: Cost = 5087465.75
Iteration 282: Cost = 5078520.23
Iteration 283: Cost = 5069716.36
Iteration 284: Cost = 5061051.60
Iteration 285: Cost = 5052523.44
Iteration 286: Cost = 5044129.41
Iteration 287: Cost = 5035867.12
Iteration 288: Cost = 5027734.19
Iteration 289: Cost = 5019728.30
Iteration 290: Cost = 5011847.18
Iteration 291: Cost = 5004088.60
Iteration 292: Cost = 4996450.36
Iteration 293: Cost = 4988930.31
Iteration 294: Cost = 4981526.35
Iteration 295: Cost = 4974236.41
Iteration 296: Cost = 4967058.46
Iteration 297: Cost = 4959990.51
Iteration 298: Cost = 4953030.60
Iteration 299: Cost = 4946176.83
Iteration 300: Cost = 4939427.30
Iteration 301: Cost = 4932780.18
Iteration 302: Cost = 4926233.66
Iteration 303: Cost = 4919785.96
Iteration 304: Cost = 4913435.33
Iteration 305: Cost = 4907180.08
Iteration 306: Cost = 4901018.52
Iteration 307: Cost = 4894949.00
Iteration 308: Cost = 4888969.92
Iteration 309: Cost = 4883079.70
Iteration 310: Cost = 4877276.76
Iteration 311: Cost = 4871559.60
Iteration 312: Cost = 4865926.71
Iteration 313: Cost = 4860376.63
Iteration 314: Cost = 4854907.91
Iteration 315: Cost = 4849519.15
Iteration 316: Cost = 4844208.95
Iteration 317: Cost = 4838975.95
Iteration 318: Cost = 4833818.82
Iteration 319: Cost = 4828736.24
Iteration 320: Cost = 4823726.94
Iteration 321: Cost = 4818789.65
Iteration 322: Cost = 4813923.12
Iteration 323: Cost = 4809126.15
Iteration 324: Cost = 4804397.53
Iteration 325: Cost = 4799736.11
Iteration 326: Cost = 4795140.73
Iteration 327: Cost = 4790610.26
Iteration 328: Cost = 4786143.59
Iteration 329: Cost = 4781739.65
Iteration 330: Cost = 4777397.36
Iteration 331: Cost = 4773115.67
Iteration 332: Cost = 4768893.57
Iteration 333: Cost = 4764730.04
Iteration 334: Cost = 4760624.09
Iteration 335: Cost = 4756574.75
Iteration 336: Cost = 4752581.07
Iteration 337: Cost = 4748642.11
Iteration 338: Cost = 4744756.96
Iteration 339: Cost = 4740924.71
Iteration 340: Cost = 4737144.49
Iteration 341: Cost = 4733415.41
Iteration 342: Cost = 4729736.63
Iteration 343: Cost = 4726107.31
Iteration 344: Cost = 4722526.62
Iteration 345: Cost = 4718993.78
Iteration 346: Cost = 4715507.97
Iteration 347: Cost = 4712068.42
Iteration 348: Cost = 4708674.38
Iteration 349: Cost = 4705325.09
Iteration 350: Cost = 4702019.82
Iteration 351: Cost = 4698757.83
Iteration 352: Cost = 4695538.44
Iteration 353: Cost = 4692360.93
Iteration 354: Cost = 4689224.63
Iteration 355: Cost = 4686128.87
Iteration 356: Cost = 4683072.98
Iteration 357: Cost = 4680056.32
Iteration 358: Cost = 4677078.25
Iteration 359: Cost = 4674138.16
Iteration 360: Cost = 4671235.42
Iteration 361: Cost = 4668369.44
Iteration 362: Cost = 4665539.63
Iteration 363: Cost = 4662745.41
Iteration 364: Cost = 4659986.20
Iteration 365: Cost = 4657261.46
Iteration 366: Cost = 4654570.62
Iteration 367: Cost = 4651913.15
Iteration 368: Cost = 4649288.53
Iteration 369: Cost = 4646696.22
Iteration 370: Cost = 4644135.73
Iteration 371: Cost = 4641606.54
Iteration 372: Cost = 4639108.17
Iteration 373: Cost = 4636640.14
Iteration 374: Cost = 4634201.96
Iteration 375: Cost = 4631793.17
Iteration 376: Cost = 4629413.31
Iteration 377: Cost = 4627061.94
Iteration 378: Cost = 4624738.60
Iteration 379: Cost = 4622442.87
Iteration 380: Cost = 4620174.32
Iteration 381: Cost = 4617932.52
Iteration 382: Cost = 4615717.07
Iteration 383: Cost = 4613527.57
Iteration 384: Cost = 4611363.60
Iteration 385: Cost = 4609224.80
Iteration 386: Cost = 4607110.76
Iteration 387: Cost = 4605021.12
Iteration 388: Cost = 4602955.50
Iteration 389: Cost = 4600913.54
Iteration 390: Cost = 4598894.88
Iteration 391: Cost = 4596899.17
Iteration 392: Cost = 4594926.07
Iteration 393: Cost = 4592975.23
Iteration 394: Cost = 4591046.33
Iteration 395: Cost = 4589139.04
Iteration 396: Cost = 4587253.03
Iteration 397: Cost = 4585387.98
Iteration 398: Cost = 4583543.60
Iteration 399: Cost = 4581719.56
Iteration 400: Cost = 4579915.58
Iteration 401: Cost = 4578131.36
Iteration 402: Cost = 4576366.60
Iteration 403: Cost = 4574621.03
Iteration 404: Cost = 4572894.35
Iteration 405: Cost = 4571186.31
Iteration 406: Cost = 4569496.62
Iteration 407: Cost = 4567825.03
Iteration 408: Cost = 4566171.26
Iteration 409: Cost = 4564535.07
Iteration 410: Cost = 4562916.19
Iteration 411: Cost = 4561314.39
Iteration 412: Cost = 4559729.42
Iteration 413: Cost = 4558161.04
Iteration 414: Cost = 4556609.01
Iteration 415: Cost = 4555073.10
Iteration 416: Cost = 4553553.08
Iteration 417: Cost = 4552048.73
Iteration 418: Cost = 4550559.83
Iteration 419: Cost = 4549086.16
Iteration 420: Cost = 4547627.51
Iteration 421: Cost = 4546183.67
Iteration 422: Cost = 4544754.44
Iteration 423: Cost = 4543339.60
Iteration 424: Cost = 4541938.97
Iteration 425: Cost = 4540552.34
Iteration 426: Cost = 4539179.52
Iteration 427: Cost = 4537820.33
Iteration 428: Cost = 4536474.58
Iteration 429: Cost = 4535142.08
Iteration 430: Cost = 4533822.65
Iteration 431: Cost = 4532516.12
Iteration 432: Cost = 4531222.31
Iteration 433: Cost = 4529941.06
Iteration 434: Cost = 4528672.18
Iteration 435: Cost = 4527415.53
Iteration 436: Cost = 4526170.92
Iteration 437: Cost = 4524938.21
Iteration 438: Cost = 4523717.23
Iteration 439: Cost = 4522507.84
Iteration 440: Cost = 4521309.86
Iteration 441: Cost = 4520123.17
Iteration 442: Cost = 4518947.60
Iteration 443: Cost = 4517783.01
Iteration 444: Cost = 4516629.26
Iteration 445: Cost = 4515486.21
Iteration 446: Cost = 4514353.72
Iteration 447: Cost = 4513231.65
Iteration 448: Cost = 4512119.87
Iteration 449: Cost = 4511018.25
Iteration 450: Cost = 4509926.65
Iteration 451: Cost = 4508844.95
Iteration 452: Cost = 4507773.02
Iteration 453: Cost = 4506710.73
Iteration 454: Cost = 4505657.98
Iteration 455: Cost = 4504614.62
Iteration 456: Cost = 4503580.56
Iteration 457: Cost = 4502555.66
Iteration 458: Cost = 4501539.82
Iteration 459: Cost = 4500532.93
Iteration 460: Cost = 4499534.86
Iteration 461: Cost = 4498545.52
Iteration 462: Cost = 4497564.79
Iteration 463: Cost = 4496592.57
Iteration 464: Cost = 4495628.75
Iteration 465: Cost = 4494673.24
Iteration 466: Cost = 4493725.92
Iteration 467: Cost = 4492786.70
Iteration 468: Cost = 4491855.49
Iteration 469: Cost = 4490932.18
Iteration 470: Cost = 4490016.69
Iteration 471: Cost = 4489108.90
Iteration 472: Cost = 4488208.75
Iteration 473: Cost = 4487316.12
Iteration 474: Cost = 4486430.94
Iteration 475: Cost = 4485553.12
Iteration 476: Cost = 4484682.56
Iteration 477: Cost = 4483819.18
Iteration 478: Cost = 4482962.91
Iteration 479: Cost = 4482113.65
Iteration 480: Cost = 4481271.32
Iteration 481: Cost = 4480435.84
Iteration 482: Cost = 4479607.14
Iteration 483: Cost = 4478785.13
Iteration 484: Cost = 4477969.75
Iteration 485: Cost = 4477160.90
Iteration 486: Cost = 4476358.52
Iteration 487: Cost = 4475562.53
Iteration 488: Cost = 4474772.86
Iteration 489: Cost = 4473989.45
Iteration 490: Cost = 4473212.21
Iteration 491: Cost = 4472441.08
Iteration 492: Cost = 4471675.99
Iteration 493: Cost = 4470916.87
Iteration 494: Cost = 4470163.65
Iteration 495: Cost = 4469416.28
Iteration 496: Cost = 4468674.68
Iteration 497: Cost = 4467938.80
Iteration 498: Cost = 4467208.56
Iteration 499: Cost = 4466483.91
Iteration 500: Cost = 4465764.78
Iteration 501: Cost = 4465051.12
Iteration 502: Cost = 4464342.86
Iteration 503: Cost = 4463639.95
Iteration 504: Cost = 4462942.33
Iteration 505: Cost = 4462249.94
Iteration 506: Cost = 4461562.73
Iteration 507: Cost = 4460880.64
Iteration 508: Cost = 4460203.61
Iteration 509: Cost = 4459531.60
Iteration 510: Cost = 4458864.54
Iteration 511: Cost = 4458202.39
Iteration 512: Cost = 4457545.10
Iteration 513: Cost = 4456892.61
Iteration 514: Cost = 4456244.87
Iteration 515: Cost = 4455601.84
Iteration 516: Cost = 4454963.46
Iteration 517: Cost = 4454329.68
Iteration 518: Cost = 4453700.47
Iteration 519: Cost = 4453075.76
Iteration 520: Cost = 4452455.52
Iteration 521: Cost = 4451839.71
Iteration 522: Cost = 4451228.26
Iteration 523: Cost = 4450621.15
Iteration 524: Cost = 4450018.32
Iteration 525: Cost = 4449419.73
Iteration 526: Cost = 4448825.34
Iteration 527: Cost = 4448235.11
Iteration 528: Cost = 4447649.00
Iteration 529: Cost = 4447066.96
Iteration 530: Cost = 4446488.95
Iteration 531: Cost = 4445914.94
Iteration 532: Cost = 4445344.88
Iteration 533: Cost = 4444778.74
Iteration 534: Cost = 4444216.47
Iteration 535: Cost = 4443658.05
Iteration 536: Cost = 4443103.42
Iteration 537: Cost = 4442552.55
Iteration 538: Cost = 4442005.42
Iteration 539: Cost = 4441461.97
Iteration 540: Cost = 4440922.18
Iteration 541: Cost = 4440386.01
Iteration 542: Cost = 4439853.43
Iteration 543: Cost = 4439324.40
Iteration 544: Cost = 4438798.88
Iteration 545: Cost = 4438276.84
Iteration 546: Cost = 4437758.26
Iteration 547: Cost = 4437243.10
Iteration 548: Cost = 4436731.32
Iteration 549: Cost = 4436222.89
Iteration 550: Cost = 4435717.78
Iteration 551: Cost = 4435215.97
Iteration 552: Cost = 4434717.41
Iteration 553: Cost = 4434222.09
Iteration 554: Cost = 4433729.96
Iteration 555: Cost = 4433241.01
Iteration 556: Cost = 4432755.19
Iteration 557: Cost = 4432272.49
Iteration 558: Cost = 4431792.87
Iteration 559: Cost = 4431316.31
Iteration 560: Cost = 4430842.77
Iteration 561: Cost = 4430372.23
Iteration 562: Cost = 4429904.67
Iteration 563: Cost = 4429440.05
Iteration 564: Cost = 4428978.34
Iteration 565: Cost = 4428519.54
Iteration 566: Cost = 4428063.59
Iteration 567: Cost = 4427610.49
Iteration 568: Cost = 4427160.21
Iteration 569: Cost = 4426712.71
Iteration 570: Cost = 4426267.98
Iteration 571: Cost = 4425825.99
Iteration 572: Cost = 4425386.72
Iteration 573: Cost = 4424950.14
Iteration 574: Cost = 4424516.23
Iteration 575: Cost = 4424084.97
Iteration 576: Cost = 4423656.32
Iteration 577: Cost = 4423230.28
Iteration 578: Cost = 4422806.82
Iteration 579: Cost = 4422385.91
Iteration 580: Cost = 4421967.53
Iteration 581: Cost = 4421551.67
Iteration 582: Cost = 4421138.29
Iteration 583: Cost = 4420727.38
Iteration 584: Cost = 4420318.92
Iteration 585: Cost = 4419912.89
Iteration 586: Cost = 4419509.26
Iteration 587: Cost = 4419108.01
Iteration 588: Cost = 4418709.13
Iteration 589: Cost = 4418312.59
Iteration 590: Cost = 4417918.38
Iteration 591: Cost = 4417526.48
Iteration 592: Cost = 4417136.86
Iteration 593: Cost = 4416749.50
Iteration 594: Cost = 4416364.40
Iteration 595: Cost = 4415981.52
Iteration 596: Cost = 4415600.86
Iteration 597: Cost = 4415222.38
Iteration 598: Cost = 4414846.08
Iteration 599: Cost = 4414471.94
Iteration 600: Cost = 4414099.94
Iteration 601: Cost = 4413730.05
Iteration 602: Cost = 4413362.27
Iteration 603: Cost = 4412996.58
Iteration 604: Cost = 4412632.95